name: Build Release Package
on:
  push:
    branches:
      - test2

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
